version: '3.8'

services:
  mcp-debug-wizard:
    build: .
    container_name: "MCP-Suite-Debug-Wizard"
    ports:
      - "8094:8094"  # Main web interface (avoiding conflicts)
      - "8095:8095"  # Mock server
      - "8096:8096"  # Proxy server
    volumes:
      # Mount host MCP configurations (read-only)
      - ~/.claude.json:/mcp-configs/.claude.json:ro
      - ~/.gemini:/mcp-configs/.gemini:ro
      # Mount workspace for testing (read-write)
      - ./workspace:/workspace:rw
      # Mount logs directory
      - ./logs:/app/logs:rw
      # Mount host user's .cache for UV/pip cache (optional performance boost)
      - ~/.cache:/home/mcpuser/.cache:rw
    environment:
      - MCP_CONFIG_DIR=/mcp-configs
      - WORKSPACE_DIR=/workspace
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    networks:
      - mcp-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8094/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Run all three services separately for debugging
  mcp-mock-genie:
    build: .
    container_name: "MCP-Suite-Mock-Genie"
    command: ["python", "mock_server.py"]
    ports:
      - "8095:8095"
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - mcp-net
    profiles:
      - debug

  mcp-proxy-spy:
    build: .
    container_name: "MCP-Suite-Proxy-Spy"
    command: ["python", "mcp_proxy.py"]
    ports:
      - "8096:8096"
    volumes:
      - ~/.claude.json:/mcp-configs/.claude.json:ro
      - ~/.gemini:/mcp-configs/.gemini:ro
      - ./workspace:/workspace:rw
      - ./logs:/app/logs:rw
    environment:
      - MCP_CONFIG_DIR=/mcp-configs
    networks:
      - mcp-net
    profiles:
      - debug

  mcp-web-portal:
    build: .
    container_name: "MCP-Suite-Web-Portal"
    command: ["python", "web_interface.py"]
    ports:
      - "8094:8094"
    volumes:
      - ~/.claude.json:/mcp-configs/.claude.json:ro
      - ~/.gemini:/mcp-configs/.gemini:ro
      - ./workspace:/workspace:rw
      - ./logs:/app/logs:rw
    environment:
      - MCP_CONFIG_DIR=/mcp-configs
      - MOCK_SERVER_URL=http://mcp-suite-mock-genie:8095
      - PROXY_SERVER_URL=http://mcp-suite-proxy-spy:8096
    networks:
      - mcp-net
    profiles:
      - debug
    depends_on:
      - mcp-mock-genie
      - mcp-proxy-spy

networks:
  mcp-net:
    driver: bridge